name: Test

on:
    push:
        branches:
            - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        timeout-minutes: 30
        permissions:
            contents: read
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3

            - name: Setup PNPM
              uses: pnpm/action-setup@v2.2.4
              with:
                  run_install: true

            - name: Build
              run: pnpm build
